services:
  - type: web
    name: n8n-puppeteer
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-2gc1.onrender.com
